name: coder-review
on:
  push:
    branches:
      - "**"
    paths:
      - "app/**"
      - ".github/**"

jobs:
  build:
    name: Code-Review
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello World"